# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 12.x
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
        cache: 'npm'
        
    - name: Lint
      run: npm run nx -- lint
    - name: Unit tests
      run: npm run nx -- test
    - name: Build
      run: npm run nx -- build
